-- SELECT B.CATEGORY, SUM(BS.SALES) AS TOTAL_SALES
-- FROM BOOK B
-- JOIN BOOK_SALES BS ON B.BOOK_ID = BS.BOOK_ID
-- WHERE YEAR(BS.SALES_DATE) = 2022 AND MONTH(BS.SALES_DATE) = 1
-- GROUP BY B.CATEGORY
-- ORDER BY B.CATEGORY;

-- 더 좋은 방법
-- 1. JOIN 명시
-- 2. YEAR, MONTH를 이용한 날짜 조건문
SELECT B.CATEGORY, SUM(BS.SALES) AS TOTAL_SALES
FROM BOOK B
JOIN BOOK_SALES BS ON B.BOOK_ID = BS.BOOK_ID
WHERE YEAR(BS.SALES_DATE) = 2022 AND MONTH(BS.SALES_DATE) = 1
GROUP BY B.CATEGORY
ORDER BY B.CATEGORY;
