SELECT CC.CAR_ID, CC.CAR_TYPE, FLOOR(DAILY_FEE * (1-DISCOUNT_RATE/100) * 30) AS FEE
FROM CAR_RENTAL_COMPANY_CAR CC
LEFT OUTER JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN DP ON CC.CAR_TYPE = DP.CAR_TYPE
WHERE (CC.CAR_TYPE = '세단' OR CC.CAR_TYPE = 'SUV')
    AND CC.CAR_ID NOT IN (
        SELECT CAR_ID
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
        WHERE START_DATE >= '2022-11-01' AND END_DATE <= '2022-11-30'
    )
    AND DURATION_TYPE = '30일 이상'
    AND (DAILY_FEE * (1-DISCOUNT_RATE/100)) * 30 BETWEEN 500000 AND 2000000
ORDER BY FEE DESC, CC.CAR_TYPE ASC, CC.CAR_ID DESC;