-- 코드를 입력하세요
SELECT HISTORY_ID, ROUND(DAILY_FEE*(1-COALESCE(DISCOUNT_RATE,0)/100)*DURATION) AS FEE
FROM (
    SELECT *
    FROM CAR_RENTAL_COMPANY_CAR
    WHERE CAR_TYPE = '트럭'
) C
JOIN (
    SELECT HISTORY_ID, CAR_ID, (DATEDIFF(END_DATE, START_DATE) + 1) AS DURATION,
        CASE
            WHEN DATEDIFF(END_DATE, START_DATE)+1 BETWEEN 7 AND 29 THEN '7일 이상'
            WHEN DATEDIFF(END_DATE, START_DATE)+1 BETWEEN 30 AND 89 THEN '30일 이상'
            WHEN DATEDIFF(END_DATE, START_DATE)+1 >= 90 THEN '90일 이상'
            ELSE 'N'
        END AS DURATION_TYPE
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
) H USING(CAR_ID)
LEFT JOIN (
    SELECT DURATION_TYPE, DISCOUNT_RATE
    FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
    WHERE CAR_TYPE = '트럭'
) P USING (DURATION_TYPE)
ORDER BY FEE DESC, HISTORY_ID DESC

-- 개선
SELECT HISTORY_ID, ROUND(DAILY_FEE * (1 - (COALESCE(DISCOUNT_RATE,0)/100)) * (DATEDIFF(END_DATE, START_DATE) + 1)) AS FEE
FROM CAR_RENTAL_COMPANY_CAR C
JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY H ON C.CAR_ID = H.CAR_ID
LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN P ON C.CAR_TYPE = P.CAR_TYPE
AND (CASE
        WHEN DATEDIFF(H.END_DATE, H.START_DATE)+1 BETWEEN 7 AND 29 THEN '7일 이상'
        WHEN DATEDIFF(H.END_DATE, H.START_DATE)+1 BETWEEN 30 AND 89 THEN '30일 이상'
        WHEN DATEDIFF(H.END_DATE, H.START_DATE)+1 >= 90 THEN '90일 이상'
        ELSE 'N'
    END = DURATION_TYPE
)
WHERE C.CAR_TYPE = '트럭'
ORDER BY FEE DESC, HISTORY_ID DESC