-- 코드를 입력하세요
SELECT (CONCAT('/home/grep/src/', UGF.BOARD_ID, '/', FILE_ID, FILE_NAME, FILE_EXT)) AS FILE_ID
FROM USED_GOODS_FILE UGF
JOIN (
    SELECT BOARD_ID
    FROM USED_GOODS_BOARD
    ORDER BY VIEWS DESC
    LIMIT 1
) UGB ON UGF.BOARD_ID = UGB.BOARD_ID
ORDER BY FILE_ID DESC

-- 방법 2. JOIN 없이 서브쿼리 이용
-- 코드를 입력하세요
SELECT (CONCAT('/home/grep/src/', UGF.BOARD_ID, '/', FILE_ID, FILE_NAME, FILE_EXT)) AS FILE_ID
FROM USED_GOODS_FILE UGF
WHERE UGF.BOARD_ID = (
    SELECT BOARD_ID
    FROM USED_GOODS_BOARD
    ORDER BY VIEWS DESC
    LIMIT 1
)
ORDER BY FILE_ID DESC
